// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment(
      'ANDROID_APP_API_KEY',
      defaultValue: '',
    ),
    appId: String.fromEnvironment(
      'ANDROID_APP_APP_ID',
      defaultValue: '',
    ),
    messagingSenderId: String.fromEnvironment(
      'ANDROID_APP_MESSAGING_SENDER_ID',
      defaultValue: '',
    ),
    projectId: String.fromEnvironment(
      'ANDROID_APP_PROJECT_ID',
      defaultValue: '',
    ),
    storageBucket: String.fromEnvironment(
      'ANDROID_APP_STORAGE_BUCKET',
      defaultValue: '',
    ),
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment(
      'IOS_APP_API_KEY',
      defaultValue: '',
    ),
    appId: String.fromEnvironment(
      'IOS_APP_APP_ID',
      defaultValue: '',
    ),
    messagingSenderId: String.fromEnvironment(
      'IOS_APP_MESSAGING_SENDER_ID',
      defaultValue: '',
    ),
    projectId: String.fromEnvironment(
      'IOS_APP_PROJECT_ID',
      defaultValue: '',
    ),
    storageBucket: String.fromEnvironment(
      'IOS_APP_STORAGE_BUCKET',
      defaultValue: '',
    ),
    iosClientId: String.fromEnvironment(
      'IOS_APP_CLIENT_ID',
      defaultValue: '',
    ),
    iosBundleId: String.fromEnvironment(
      'IOS_APP_BUNDLE_ID',
      defaultValue: '',
    ),
  );
}
